export const DISTRIBUTE_CARDS = 'DISTRIBUTE_CARDS';
export const SET_DICE_OUTCOME = 'SET_DICE_OUTCOME';
export const SET_CARD_DECKS = 'SET_CARD_DECKS';
export const SET_SELECTED_CARD_SET = 'SET_SELECTED_CARD_SET';
export const SET_GAME_SCORES = 'SET_GAME_SCORES';
export const RESET_GAME_PHASE = 'RESET_GAME_PHASE';
export const SET_STAGEG_GAME_RESULT = 'SET_STAGEG_GAME_RESULT';
